In [23]:
import numpy as np

# Calculating Integrals using Recurrence Relation

<p>In this problem we will use recurrence relations to compute an integral and determine the relative and absolute errors associated with each of them.
Consider the integral
$$
 I_k=\int_{0}^1 x^k e^{x-1} dx
$$  </p>

In the following, you will use two different methods to approximate the above integral:


#### a) Forward Recurrence Relation:
    
    
Compute the array <code>If</code> such that $\textrm{If}= [I_1, I_2, I_3, ...]$.  

Evaluate the integrals $I_n$
   using the <strong>Forward Recurrence Relation</strong> defined as:
   
$$ I_k = 1 - kI_{k-1} \ \ \ \ \ \ \ \forall\ \ \ \   k \in {1,2,3,..... , {\rm nmax} }. $$ 

where you know the value of $I_0 = 1-1/e$. 

Use the `nmax` value provided in the PrairieLearn question (which is the same used by the autograder to check your code).


In [30]:
nmax = 39

In [31]:
# add your code here
If = [1-(1/np.exp(1))]
for k in range(1,nmax+1):
    If.append(1-If[-1]*k)
If = np.array(If[1:])
print(If)

[ 3.67879441e-01  2.64241118e-01  2.07276647e-01  1.70893412e-01
  1.45532941e-01  1.26802357e-01  1.12383504e-01  1.00931967e-01
  9.16122930e-02  8.38770701e-02  7.73522294e-02  7.17732477e-02
  6.69477800e-02  6.27310804e-02  5.90337936e-02  5.54593017e-02
  5.71918706e-02 -2.94536708e-02  1.55961974e+00 -3.01923949e+01
  6.35040293e+02 -1.39698864e+04  3.21308388e+05 -7.71140031e+06
  1.92785009e+08 -5.01241023e+09  1.35335076e+11 -3.78938213e+12
  1.09892082e+14 -3.29676246e+15  1.02199636e+17 -3.27038836e+18
  1.07922816e+20 -3.66937574e+21  1.28428151e+23 -4.62341343e+24
  1.71066297e+26 -6.50051928e+27  2.53520252e+29]


#### b) Backward Recurrence Relation:
    
Compute the array <code>Ib</code> such that $\textrm{Ib}= [I_1, I_2, I_3, ...]$. 

Evaluate the integrals $I_n$
   using the <strong>Backward Recurrence Relation</strong> defined as:
   
   $$ I_{k-1} = \left(\frac{1-I_k}{k}\right)  \ \ \ \ \ \forall \ \ \ \ \ \ k \in { {\rm nmax}, ......... , 1}. $$
   
   
   Assume that $I_k = 0$ for $k={\rm nmax}$. 

In [32]:
# add your code here
Ib = [0]
for k in range(nmax,1,-1):
    Ib.append((1-Ib[-1])/k)
Ib = np.array(Ib[::-1])
Ib


array([0.36787944, 0.26424112, 0.20727665, 0.17089341, 0.14553294,
       0.12680236, 0.1123835 , 0.10093197, 0.09161229, 0.08387707,
       0.07735223, 0.07177325, 0.0669477 , 0.06273216, 0.05901754,
       0.05571935, 0.05277112, 0.05011985, 0.04772276, 0.04554488,
       0.04355743, 0.04173644, 0.04006181, 0.03851655, 0.03708621,
       0.03575842, 0.03452253, 0.03336929, 0.03229068, 0.03127967,
       0.03033011, 0.02943654, 0.02859416, 0.02779868, 0.02704628,
       0.02633403, 0.02564103, 0.02564103, 0.        ])

#### Exact integrals
Calculate the exact integral using the provided function <code>func_int</code> which takes the input $k$ and returns the integral $I_k$.
    Calculate the integral for all the k values in the array <code>[1, 2, 3,..., nmax]</code>. Store your results in the array `Iexact`

In [7]:
from scipy.integrate import quad

def func_int(k):
    ans, err = quad(lambda x: (x ** k) * np.exp(x-1), 0, 1)
    return ans


In [8]:
# add your code here
Iexact = [func_int(k) for k in range(1,nmax+1)]
Iexact = np.array(Iexact)
print(len(Iexact), len(Ib), len(If))

39 39 39


Note: In the following error calculations, use the values generated by the function <code>func_int</code> to be the true values.     

#### Absolute error

Calculate the absolute errors associated with the forward recurrence relation and store them in the array 
     <code>abserrf</code> 

In [9]:
# add your code here
abserrf = np.abs(Iexact - If)
abserrf

array([0.00000000e+00, 5.55111512e-17, 8.32667268e-17, 3.33066907e-16,
       1.47104551e-15, 8.96505092e-15, 6.26304564e-14, 5.01140796e-13,
       4.51014226e-12, 4.51014642e-11, 4.96116051e-10, 5.95339290e-09,
       7.73941076e-08, 1.08351751e-06, 1.62527626e-05, 2.60044202e-04,
       4.42075143e-03, 7.95735257e-02, 1.51189699e+00, 3.02379398e+01,
       6.34996735e+02, 1.39699282e+04, 3.21308348e+05, 7.71140035e+06,
       1.92785009e+08, 5.01241023e+09, 1.35335076e+11, 3.78938213e+12,
       1.09892082e+14, 3.29676246e+15, 1.02199636e+17, 3.27038836e+18,
       1.07922816e+20, 3.66937574e+21, 1.28428151e+23, 4.62341343e+24,
       1.71066297e+26, 6.50051928e+27, 2.53520252e+29])

Calculate the absolute errors associated with the backward recurrence relation and store them in the array 
     <code>abserrb</code>   

In [10]:
# add your code here
abserrb =  np.abs(Iexact - Ib)
abserrb

array([0.00000000e+00, 5.55111512e-17, 2.77555756e-17, 5.55111512e-17,
       0.00000000e+00, 2.77555756e-17, 1.38777878e-17, 1.38777878e-17,
       0.00000000e+00, 0.00000000e+00, 2.77555756e-17, 0.00000000e+00,
       0.00000000e+00, 1.38777878e-17, 2.77555756e-17, 1.38777878e-17,
       6.93889390e-18, 2.08166817e-17, 1.38777878e-17, 6.93889390e-18,
       1.38777878e-17, 1.38777878e-17, 1.38777878e-17, 1.38777878e-17,
       1.38777878e-17, 6.93889390e-18, 6.93889390e-18, 0.00000000e+00,
       2.08166817e-17, 3.05311332e-16, 9.85322934e-15, 3.14800269e-13,
       1.03889050e-11, 3.53222378e-10, 1.23627837e-08, 4.45060214e-07,
       1.64672279e-05, 6.25754661e-04, 2.44044318e-02])

#### Relative error

Calculate the relative errors associated with the forward recurrence relation and store them in the array 
     <code>relerrf</code> 

In [12]:
# add your code here
relerrf = abserrf / np.abs(Iexact)
relerrf

array([0.00000000e+00, 2.10077643e-16, 4.01717840e-16, 1.94897453e-15,
       1.01079900e-14, 7.07009804e-14, 5.57292255e-13, 4.96513452e-12,
       4.92307540e-11, 5.37709104e-10, 6.41372664e-09, 8.29472345e-08,
       1.15603829e-06, 1.72721207e-05, 2.75388679e-04, 4.66703615e-03,
       8.37721750e-02, 1.58766472e+00, 3.16808400e+01, 6.63915177e+02,
       1.45783778e+04, 3.34717747e+05, 8.02031524e+06, 2.00210041e+08,
       5.19829300e+09, 1.40174245e+11, 3.92019629e+12, 1.13558978e+14,
       3.40321388e+15, 1.05396318e+17, 3.36957705e+18, 1.11099616e+20,
       3.77429618e+21, 1.31998213e+23, 4.74845731e+24, 1.75571009e+26,
       6.66730369e+27, 2.59862037e+29, 1.03882874e+31])

Calculate the absolute errors associated with the backward recurrence relation and store them in the array 
     <code>relerrb</code>   

In [13]:
# add your code here
relerrb = abserrb / np.abs(Iexact)
relerrb

array([0.00000000e+00, 2.10077643e-16, 1.33905947e-16, 3.24829089e-16,
       0.00000000e+00, 2.18888484e-16, 1.23485986e-16, 1.37496456e-16,
       0.00000000e+00, 0.00000000e+00, 3.58820632e-16, 0.00000000e+00,
       0.00000000e+00, 2.21222845e-16, 4.70293665e-16, 2.49065878e-16,
       1.31490368e-16, 4.15338028e-16, 2.90800218e-16, 1.52352872e-16,
       3.18608935e-16, 3.32510075e-16, 3.46409403e-16, 3.60307122e-16,
       3.74203407e-16, 1.94049204e-16, 2.00996127e-16, 0.00000000e+00,
       6.44665374e-16, 9.76069420e-15, 3.24866278e-13, 1.06942005e-11,
       3.63322660e-10, 1.27064454e-08, 4.57097222e-07, 1.69008617e-05,
       6.41809705e-04, 2.50149064e-02, 1.00000000e+00])